### ISSUE TITLE
Dijagram Aktivnosti

### ISSUE THREAD

**Issue by aprasovic1** [bkarahodzi1/OOAD#30]
- [x] Koristiti isti font
- [x] Dijagram 4: Nakon potvrde plaćanja ide odmah na fork  
- [x] Dijagram 5: Izbaciti kraj interakcije
- [x] Dijagram 5: Fork umjesto uslova
- [x] Dijagram 6: Fork umjesto uslova
- [x] Dijagram 10: Paralelne akcije za čekanje na odobrenje admina (poput dijagrama 2)

**Comment by imranspahic** [comment]
@bkarahodzi1 Možeš li ispraviti prve dvije stavke ili su već ispravljene pošto nisu označene sa done

**Comment by bkarahodzi1** [comment]
@imranspahic evo označio sam font, a 4. nije moj

**Comment by imranspahic** [comment]
@aprasovic1

**Comment by aprasovic1** [comment]
Završen dijagram 4 @imranspahic
