### ISSUE TITLE
Dijagram klasa

### ISSUE THREAD

**Issue by aprasovic1** [bkarahodzi1/OOAD#35]
Deadline 17.4.2023.
- [x] Dijagram klasa

[https://online.visual-paradigm.com/share.jsp?id=323437373934312d37](https://l.facebook.com/l.php?u=https%3A%2F%2Fonline.visual-paradigm.com%2Fshare.jsp%3Fid%3D323437373934312d37%26fbclid%3DIwAR2JQYso45uKsxnCzQV9KH8YKUv6ijvVd5YtF5JMqdJDXAo2nLu_h6tl9Aw&h=AT0P5Z0ML2hVdDxJaaHX4uLILYWgRTvMhQ5YJYBIozhHuAr-24tTRjivD89yyPFfvubEJWw-Iz6ZZB6RpAsMNdBjfQhnLSWYJ6d-aIyF9dAtPvOo-eOkhL9UkdmmLwd_d7x4WvV00O7ujoT-oQMTPhJuxQo)

**Comment by Griza20** [comment]
Zavrseno.
