### ISSUE TITLE
SOLID principi

### ISSUE THREAD

**Issue by aprasovic1** [bkarahodzi1/OOAD#36]
Deadline 30.4.2023.

- [x] Svi SOLID principi trebaju biti ispunjeni u dijagramu klasa. U svrhu osiguranja ispunjavanja SOLID principa, potrebno je definisati kratki dokument (1 do 1.5 stranica) u kome će se opisati klase modela sistema s aspekta svih pojedinačnih SOLID principa i obrazložiti razlozi zbog kojih su principi zadovoljeni.

**Comment by imranspahic** [comment]
Završeno.
