### ISSUE TITLE
Analiza i Dizajn Sistema

### ISSUE THREAD

**Issue by ibecir** [bkarahodzi1/OOAD#38]
1. Klasa Student - atribut points, zasto na studentu, to samo ima veze sa kursem koji uzima a ne sa samim studentom.
                            - atribut subscribedCourses - dodati i atribut koji govori u kojoj akademskoj godini, kojem semestru se izma kurs, inace ovaj citav sistem ima samo smisla na nivou jedne cjeline, ne postize e efekat studentskog sistema
2. Klasa Profesor - atribut studentInCourses - pogresno totalno, student uzima kurseve a profesor ih drzi, studenti nisu vezani za profesora nego za kurs koji uzimaju a profesor taj kurs drzi. 
3. Kurs je klasa u kojoj se samo drze podatci o samom kursu, svi podatci vezani za studente, poene, kvizove moraju se drzati u nekoj novoj klasi koja za tu godinu, za taj ciklus kursa implementira i kvizove i sve ostalo. Ideja je da profesor implementira kurs kako on zeli, i da u naradenoj iteraciji moze mjenjati samu strukturu ocjenjivanja.

Ovo su neka moja zapazanja koja su mozda pogresna i moza vas sistem ima neku drugu funkciju. Cini mi se da ste zanemarili aspekt akademskih godina. Ako u kojem slucaju, vas sistem posmatrate kao c2 kurseve i ne zelite da uopste obracate paznju na akadamske godine i historiju studenata onda sam ja u krivu.

**Comment by imranspahic** [comment]
Nismo zamislili sistem kao studentski sistem - već kao c2 kursevi ili nešto na fazom Udemy kurseva, što smo već naglasili, pa nam akademske godine, semestri ili ocjenjivanja ne postoje.
Ostale neke stavke će biti ispravljene i proširene.
