### ISSUE TITLE
Dijagram sekvenci

### ISSUE THREAD

**Issue by ibecir** [bkarahodzi1/OOAD#46]
1. Ime akcije je metoda koja prima i vraca parametre a ne objasnjenje sta radi ta metoda

**Comment by ibecir** [comment]
Strukturalni patterni
--------------------

Treba nam dijagram klasa za strukturalne pattere koje ste odabrali

**Comment by Griza20** [comment]
Ovo je davno prepravljeno i pregledano, ali issue nikad nije zatvoren.
