### ISSUE TITLE
Dijagram aktivnosti za funkcionalnost 2. Registracija korisničkog računa

### ISSUE THREAD

**Issue by imranspahic** [bkarahodzi1/OOAD#6]
- [x] Kreirati novi branch
- [x] Pushati odrađen dijagram aktivnosti (exportovati i .vpd fajl i .png sliku)
- [x] Dijagram aktivnosti treba da se nalazi u korektnom folderu ActivityDiagram i sa imenom 1.vpd i 1.png (redni broj funkcionalnosti)
- [x] Kreirati pull request na main (ne zatvarati već ostavljati open pull request na review)

**Comment by Griza20** [comment]
Završeno.

**Comment by imranspahic** [comment]
@Griza20 sljedeći put koristi ovamo direktno opciju da kreiras branch -> Create a branch
i imenuj bolje pull request title
Npr: Zavšen dijagram aktivnosti za funkcionalnost 2. Registracija korisničkog računa
<img width="327" alt="image" src="https://user-images.githubusercontent.com/62642796/228682343-01083b76-57d1-42b2-bb48-0d48161576ae.png">
